theme: jekyll-theme-slate
logo: https://vignette.wikia.nocookie.net/theoutsiders/images/3/35/Johnny.jpg/revision/latest?cb=20110626230953
description: All About My Family!
show_downloads: false
google_analytics: true
